# Loading Dataset

In [6]:
import pandas as pd
import numpy as np

In [7]:
prod = pd.read_csv("../Raw Dataset/omni_products.csv")

ord = pd.read_csv("../Raw Dataset/omni_orders.csv")

cust = pd.read_csv("../Raw Dataset/omni_customers.csv")

ord_it = pd.read_csv("../Raw Dataset/omni_order_items.csv")

inv = pd.read_csv("../Raw Dataset/omni_inventory.csv")

inv_move = pd.read_csv("../Raw Dataset/omni_inventory_movements.csv")

store = pd.read_csv("../Raw Dataset/omni_stores.csv")

ware = pd.read_csv("../Raw Dataset/omni_warehouses.csv")

# Customers Table Understanding & Initial Checks

In [8]:
print("Initial Shape:", cust.shape)

Initial Shape: (5000, 4)

In [9]:
cust.head()

  customer_id  customer_name       city signup_date
0   CUST00000    Arjun Mehta     Mumbai  2023-01-05
1   CUST00001    Wei Johnson    Chennai  2023-09-13
2   CUST00002     Chen Patel  Bangalore  2023-03-18
3   CUST00003  Olivia Kovacs       Pune  2023-07-12
4   CUST00004    Emma Kovacs    Chennai  2022-02-06

In [10]:
cust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5000 non-null   object
 1   customer_name  5000 non-null   object
 2   city           5000 non-null   object
 3   signup_date    5000 non-null   object
dtypes: object(4)
memory usage: 156.4+ KB

In [11]:
cust.isnull().sum()

customer_id      0
customer_name    0
city             0
signup_date      0
dtype: int64

### Notes:
- All unique customer_ID. perfect for primary key constraint. 
- Signup date dtype is object which needs to be corrected.

# Order Table Understanding & Initial Checks

In [12]:
print("Initial Shape:", ord.shape)

Initial Shape: (50000, 6)

In [13]:
ord.head(10)

     order_id customer_id  order_date channel  store_id order_status
0  ORD0000000   CUST03080  2024-09-06   Store  STORE038     Returned
1  ORD0000001   CUST00191  2023-06-01   Store  STORE009    Cancelled
2  ORD0000002   CUST02367  2024-04-13   Store  STORE029    Cancelled
3  ORD0000003   CUST03515  2024-09-05  Online       NaN    Delivered
4  ORD0000004   CUST00780  2024-04-16   Store  STORE004    Delivered
5  ORD0000005   CUST00613  2024-08-23     App       NaN    Delivered
6  ORD0000006   CUST03959  2024-07-25  Online       NaN    Cancelled
7  ORD0000007   CUST03660  2023-03-06  Online       NaN     Returned
8  ORD0000008   CUST04130  2024-05-10     App       NaN    Delivered
9  ORD0000009   CUST01126  2023-10-22   Store  STORE021    Delivered

In [14]:
ord.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      50000 non-null  object
 1   customer_id   50000 non-null  object
 2   order_date    50000 non-null  object
 3   channel       50000 non-null  object
 4   store_id      16715 non-null  object
 5   order_status  50000 non-null  object
dtypes: object(6)
memory usage: 2.3+ MB

In [15]:
ord.isnull().sum()

order_id            0
customer_id         0
order_date          0
channel             0
store_id        33285
order_status        0
dtype: int64

In [16]:
ord['channel'].value_counts()

channel
Store     16715
App       16654
Online    16631
Name: count, dtype: int64

In [17]:
ord['order_status'].value_counts()

order_status
Shipped      12599
Returned     12583
Cancelled    12562
Delivered    12256
Name: count, dtype: int64

In [18]:
ord[ord.duplicated(keep=False)]

Empty DataFrame
Columns: [order_id, customer_id, order_date, channel, store_id, order_status]
Index: []

### Notes:
- No duplicates found.
- order_date dtype is wrong.
- Nan value is present in store_id. Is likely because of non-store orders.

# Order Iteam Table Understanding & Initial Checks

In [19]:
print("Initial Shape:", ord_it.shape)

Initial Shape: (149958, 4)

In [20]:
ord_it.head()

   order_item_id    order_id product_id  quantity
0              1  ORD0000000  PROD00502         3
1              2  ORD0000000  PROD00666         4
2              3  ORD0000000  PROD00159         3
3              4  ORD0000000  PROD00777         1
4              5  ORD0000001  PROD00658         4

In [21]:
ord_it.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149958 entries, 0 to 149957
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_item_id  149958 non-null  int64
 1   order_id       149958 non-null  object
 2   product_id     149958 non-null  object
 3   quantity       149958 non-null  int64
dtypes: int64(2), object(2)
memory usage: 4.6+ MB

In [22]:
ord_it.isnull().sum()

order_item_id    0
order_id         0
product_id       0
quantity         0
dtype: int64

In [23]:
ord_it['quantity'].describe()

count    149958.000000
mean          2.501740
std           1.117082
min           1.000000
25%           2.000000
50%           3.000000
75%           3.000000
max           4.000000
Name: quantity, dtype: float64

### Notes:
- Only 50K order item's unique. Because of many order's in one.
- likely no invalid quantity.

# Product Table Understanding & Initial Checks

In [24]:
print("Initial Shape:", prod.shape)

Initial Shape: (800, 5)

In [25]:
prod.head()

  product_id product_name     category brand    price
0  PROD00000  Dell Item_0       Sports  Dell  1888.71
1  PROD00001  Sony Item_1  Electronics  Sony  1480.04
2  PROD00002    HP Item_2  Electronics    HP   982.42
3  PROD00003  Dell Item_3  Electronics  Dell   144.96
4  PROD00004  Puma Item_4  Electronics  Puma   533.58

In [26]:
prod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    800 non-null    object
 1   product_name  800 non-null    object
 2   category      800 non-null    object
 3   brand         800 non-null    object
 4   price         800 non-null    float64
dtypes: float64(1), object(4)
memory usage: 31.4+ KB

In [27]:
prod.isnull().sum()

product_id      0
product_name    0
category        0
brand           0
price           0
dtype: int64

In [28]:
# brand consistency check - if any brand repeat.

prod['brand'].value_counts()

brand
H&M          69
Sony         67
Dell         66
Noise        62
Samsung      61
Puma         60
Decathlon    58
Nike         57
Boat         56
HP           54
Zara         52
Ikea         49
Apple        47
Adidas       42
Name: count, dtype: int64

In [29]:
prod['category'].unique()

array(['Sports', 'Electronics', 'Home', 'Fashion'], dtype=object)

# Inventory Table Understanding & Initial Checks

In [30]:
print("Initial Shape:",inv.shape)

Initial Shape: (8000, 4)

In [31]:
inv.head()

  product_id warehouse_id  stock_quantity last_updated
0  PROD00000        WH000             263   2026-04-13
1  PROD00000        WH001             565   2026-04-13
2  PROD00000        WH002             284   2026-04-13
3  PROD00000        WH003              20   2026-04-13
4  PROD00000        WH004             203   2026-04-13

In [32]:
inv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      8000 non-null   object
 1   warehouse_id    8000 non-null   object
 2   stock_quantity  8000 non-null   int64
 3   last_updated    8000 non-null   object
dtypes: int64(1), object(3)
memory usage: 250.1+ KB

In [33]:
inv.isnull().sum()

product_id        0
warehouse_id      0
stock_quantity    0
last_updated      0
dtype: int64

In [34]:
# stock check in each warehouse

inv.groupby('warehouse_id')['stock_quantity'].sum()

warehouse_id
WH000    389718
WH001    402664
WH002    397092
WH003    406724
WH004    392143
WH005    412841
WH006    407051
WH007    392828
WH008    394715
WH009    408924
Name: stock_quantity, dtype: int64

### Notes:
- last updated dtype is wrong.

# Inventory Movement Table Understanding & Initial Checks

In [35]:
print("Initial Shape:", inv_move.shape)

Initial Shape: (100000, 5)

In [36]:
inv_move.head()

  product_id warehouse_id  change_qty   reason        date
0  PROD00578        WH005         -44  Restock  2024-04-30
1  PROD00704        WH006          82  Restock  2023-01-16
2  PROD00453        WH005           0  Restock  2023-07-20
3  PROD00702        WH007          52     Sale  2023-10-17
4  PROD00119        WH009          47     Sale  2024-10-22

In [37]:
inv_move.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   product_id    100000 non-null  object
 1   warehouse_id  100000 non-null  object
 2   change_qty    100000 non-null  int64
 3   reason        100000 non-null  object
 4   date          100000 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [38]:
inv_move.duplicated().sum()

np.int64(1)

In [39]:
inv_move['reason'].value_counts()

reason
Sale       33538
Restock    33246
Return     33216
Name: count, dtype: int64

### Notes:
- date dtype is wrong.
- Restock: stock comes IN, must be positive. Needs transformation.
- Sale: stock goes OUT, must be negative. Needs transformation.

# Store Table Understanding & Initial Checks

In [40]:
print("Initial Shape:", store.shape)

Initial Shape: (50, 3)

In [41]:
store.head()

   store_id       city       store_type
0  STORE000      Delhi  Warehouse Store
1  STORE001  Ahmedabad             Mall
2  STORE002     Jaipur  Warehouse Store
3  STORE003  Hyderabad      High Street
4  STORE004       Pune      High Street

In [42]:
store.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   store_id    50 non-null     object
 1   city        50 non-null     object
 2   store_type  50 non-null     object
dtypes: object(3)
memory usage: 1.3+ KB

In [43]:
store.isnull().sum()

store_id      0
city          0
store_type    0
dtype: int64

In [44]:
store['store_type'].unique()

array(['Warehouse Store', 'Mall', 'High Street'], dtype=object)

In [45]:
store.duplicated().sum()

np.int64(0)

# Warehouse Table Understanding & Initial Checks

In [46]:
print("Initial Shape:", ware.shape)

Initial Shape: (10, 3)

In [47]:
ware.head()

  warehouse_id       city  capacity
0        WH000    Chennai     41284
1        WH001      Delhi     30352
2        WH002  Bangalore     11943
3        WH003       Pune     31562
4        WH004       Pune     48079

In [48]:
ware.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   warehouse_id  10 non-null     object
 1   city          10 non-null     object
 2   capacity      10 non-null     int64
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes

In [49]:
ware.duplicated().sum()

np.int64(0)

In [50]:
ware['capacity'].describe()

count       10.000000
mean     34032.800000
std      13154.688702
min      11943.000000
25%      26899.000000
50%      34125.500000
75%      46380.250000
max      49488.000000
Name: capacity, dtype: float64

#  Functions

In [51]:
def clean_columns(df):
    df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
    return df

In [52]:
def clean_text(df):
    for col in df.select_dtypes(include='object'):
        df[col] = df[col].str.strip()
    return df

In [53]:
def convert_to_datetime(df, col):
    df[col] = pd.to_datetime(df[col], errors='coerce')
    return df

In [54]:
def preprocess(df):
    df = clean_columns(df)
    df = clean_text(df)
    df = df.drop_duplicates()
    return df

# Preprocessing (Cleaning columns, Cleaning Text, & Droping Duplicates- If any)

In [55]:
prod = preprocess(prod)

In [56]:
ord = preprocess(ord)

In [57]:
cust = preprocess(cust)

In [58]:
cust = preprocess(cust)

In [59]:
inv = preprocess(inv)

In [60]:
inv_move = preprocess(inv_move)

In [61]:
store = preprocess(store)

In [62]:
ware = preprocess(ware)

# Table-Specific Cleaning

In [63]:
# Customers
cust['signup_date'] = pd.to_datetime(cust['signup_date'], errors='coerce')
cust['city'] = cust['city'].fillna('N/A')

In [64]:
# Products
prod = prod[prod['price'] > 0]

prod['price'] = prod['price'].astype(float)

for col in ['brand', 'category']:
    prod[col] = prod[col].str.title()

In [65]:
# Orders
ord['order_date'] = pd.to_datetime(ord['order_date'], errors='coerce')

ord['store_id'] = ord['store_id'].str.strip().str.upper()

In [66]:
mask = (ord['channel'].isin(['Online', 'App'])) & (ord['store_id'].isna())
ord.loc[mask, 'store_id'] = 'ONLINE'

In [67]:
if 'ONLINE' not in store['store_id'].values:
    store = pd.concat([
        store,
        pd.DataFrame([{
            'store_id': 'ONLINE',
            'city': 'N/A',
            'store_type': 'Online'
        }])
    ], ignore_index=True)

In [68]:
## Validation where store_id exists
assert ord.loc[ord['store_id'].notna(), 'store_id'].isin(store['store_id']).all()

In [69]:
# Order Items
ord_it = ord_it[ord_it['quantity'] > 0]

ord_it['quantity'] = ord_it['quantity'].astype(int)

In [70]:
# Inventory
inv['last_updated'] = pd.to_datetime(inv['last_updated'], errors='coerce')

In [71]:
# Inventory Movement
inv_move['date'] = pd.to_datetime(inv_move['date'], errors='coerce')

In [72]:
inv_move = inv_move[inv_move['change_qty'] != 0]

In [73]:
mask2 = inv_move['reason'].isin(['Restock', 'Return'])
inv_move['change_qty'] = np.where(mask2,
                                 inv_move['change_qty'].abs(),
                                 -inv_move['change_qty'].abs())

In [74]:
# Stores
store['city'] = store['city'].str.title()


store['store_type'] = store['store_type'].str.title()

store['store_id'] = store['store_id'].str.strip().str.upper()

In [75]:
# Warehouses
ware = ware[ware['capacity'] > 0]

# Data Engineering

In [76]:
# Creating Revenue Column
ord_it = ord_it.merge(prod[['product_id', 'price']], on='product_id', how='left')

In [77]:
ord_it['revenue'] = ord_it['quantity'] * ord_it['price']

In [78]:
# Creating Time Feature for order_year
ord['order_year'] = ord['order_date'].dt.year

In [79]:
# Creating Time Feature for order_month
ord['order_month'] = ord['order_date'].dt.month

# Validation Checks

In [80]:
# Primary Key Checks
assert cust['customer_id'].nunique() == len(cust)

assert ord['order_id'].nunique() == len(ord)

assert prod['product_id'].nunique() == len(prod)

assert store['store_id'].nunique() == len(store)

assert ware['warehouse_id'].nunique() == len(ware)

# Foreign Key Checks

In [81]:
assert ord['customer_id'].isin(cust['customer_id']).all()

In [82]:
assert ord_it['order_id'].isin(ord['order_id']).all()

In [83]:
assert ord_it['product_id'].isin(prod['product_id']).all()

In [84]:
assert inv['product_id'].isin(prod['product_id']).all()

In [85]:
assert inv['warehouse_id'].isin(ware['warehouse_id']).all()

In [86]:
assert inv_move['warehouse_id'].isin(ware['warehouse_id']).all()

In [87]:
assert ord['store_id'].isin(store['store_id']).all()

# Saving Prepared Data In CSVs

In [88]:
cust.to_csv("clean_customers.csv", index=False, encoding='utf-8')

prod.to_csv("clean_products.csv", index=False, encoding='utf-8')

ord.to_csv("clean_orders.csv", index=False, encoding='utf-8')

ord_it.to_csv("clean_order_items.csv", index=False, encoding='utf-8')

inv.to_csv("clean_inventory.csv", index=False, encoding='utf-8')

inv_move.to_csv("clean_inventory_movements.csv", index=False, encoding='utf-8')

store.to_csv("clean_stores.csv", index=False, encoding='utf-8')

ware.to_csv("clean_warehouses.csv", index=False, encoding='utf-8')