In [1]:
import pandas as pd

In [2]:
prod = pd.read_csv("../Clean Dataset/clean_products.csv")
ord = pd.read_csv("../Clean Dataset/clean_orders.csv")
cust = pd.read_csv("../Clean Dataset/clean_customers.csv")
ord_it = pd.read_csv("../Clean Dataset/clean_order_items.csv")
inv = pd.read_csv("../Clean Dataset/clean_inventory.csv")
inv_move = pd.read_csv("../Clean Dataset/clean_inventory_movements.csv")
store = pd.read_csv("../Clean Dataset/clean_stores.csv")
ware = pd.read_csv("../Clean Dataset/clean_warehouses.csv")

1. CLEAN PRODUCTS

In [3]:
prod.head()

  product_id product_name     category brand    price
0  PROD00000  Dell Item_0       Sports  Dell  1888.71
1  PROD00001  Sony Item_1  Electronics  Sony  1480.04
2  PROD00002    HP Item_2  Electronics    Hp   982.42
3  PROD00003  Dell Item_3  Electronics  Dell   144.96
4  PROD00004  Puma Item_4  Electronics  Puma   533.58

In [4]:
print(prod.dtypes)

product_id       object
product_name     object
category         object
brand            object
price           float64
dtype: object

In [5]:
prod_max_lengths = prod.astype(str).apply(lambda x: x.str.len()).max()
print(prod_max_lengths)

product_id       9
product_name    18
category        11
brand            9
price            7
dtype: int64

2.  CLEAN ORDERS

In [20]:
ord.head()

,order_id,customer_id,order_date,channel,store_id,order_status,order_year,order_month
0,ORD0000000,CUST03080,2024-09-06,Store,STORE038,Returned,2024,9
1,ORD0000001,CUST00191,2023-06-01,Store,STORE009,Cancelled,2023,6
2,ORD0000002,CUST02367,2024-04-13,Store,STORE029,Cancelled,2024,4
3,ORD0000003,CUST03515,2024-09-05,Online,ONLINE,Delivered,2024,9
4,ORD0000004,CUST00780,2024-04-16,Store,STORE004,Delivered,2024,4

In [21]:
print(ord.dtypes)

order_id        object
customer_id     object
order_date      object
channel         object
store_id        object
order_status    object
order_year       int64
order_month      int64
dtype: object

In [22]:
ord_max_lengths = ord.astype(str).apply(lambda x: x.str.len()).max()
print(ord_max_lengths)

order_id        10
customer_id      9
order_date      10
channel          6
store_id         8
order_status     9
order_year       4
order_month      2
dtype: int64

In [23]:
ord['order_date'] = pd.to_datetime(ord['order_date'], errors = 'coerce')
ord.dtypes

order_id                object
customer_id             object
order_date      datetime64[ns]
channel                 object
store_id                object
order_status            object
order_year               int64
order_month              int64
dtype: object

3. CLEAN CUSTOMERS

In [24]:
cust.head()

  customer_id  customer_name       city signup_date
0   CUST00000    Arjun Mehta     Mumbai  2023-01-05
1   CUST00001    Wei Johnson    Chennai  2023-09-13
2   CUST00002     Chen Patel  Bangalore  2023-03-18
3   CUST00003  Olivia Kovacs       Pune  2023-07-12
4   CUST00004    Emma Kovacs    Chennai  2022-02-06

In [25]:
print(cust.dtypes)

customer_id      object
customer_name    object
city             object
signup_date      object
dtype: object

In [26]:
cust_max_lengths = cust.astype(str).apply(lambda x: x.str.len()).max()
print(cust_max_lengths)

customer_id       9
customer_name    16
city              9
signup_date      10
dtype: int64

In [27]:
cust['signup_date'] = pd.to_datetime(cust['signup_date'], errors = 'coerce')
cust.dtypes

customer_id              object
customer_name            object
city                     object
signup_date      datetime64[ns]
dtype: object

4. ORDER ITEMS

In [28]:
ord_it.head()

   order_item_id    order_id product_id  quantity   price  revenue
0              1  ORD0000000  PROD00502         3  843.38  2530.14
1              2  ORD0000000  PROD00666         4  332.01  1328.04
2              3  ORD0000000  PROD00159         3  629.83  1889.49
3              4  ORD0000000  PROD00777         1  239.59   239.59
4              5  ORD0000001  PROD00658         4  438.34  1753.36

In [29]:
print(ord_it.dtypes)

order_item_id      int64
order_id          object
product_id        object
quantity           int64
price            float64
revenue          float64
dtype: object

In [30]:
ord_it_max_lengths = ord_it.astype(str).apply(lambda x: x.str.len()).max()
print(ord_it_max_lengths)

order_item_id     6
order_id         10
product_id        9
quantity          1
price             7
revenue          18
dtype: int64

5. CLEAN INVENTORY

In [31]:
inv.head()

  product_id warehouse_id  stock_quantity last_updated
0  PROD00000        WH000             263   2026-04-13
1  PROD00000        WH001             565   2026-04-13
2  PROD00000        WH002             284   2026-04-13
3  PROD00000        WH003              20   2026-04-13
4  PROD00000        WH004             203   2026-04-13

In [32]:
print(inv.dtypes)

product_id        object
warehouse_id      object
stock_quantity     int64
last_updated      object
dtype: object

In [33]:
inv_max_lengths = inv.astype(str).apply(lambda x: x.str.len()).max()
print(inv_max_lengths)

product_id         9
warehouse_id       5
stock_quantity     3
last_updated      10
dtype: int64

In [34]:
inv['last_updated'] = pd.to_datetime(inv['last_updated'], errors= 'coerce')
inv.dtypes

product_id                object
warehouse_id              object
stock_quantity             int64
last_updated      datetime64[ns]
dtype: object

6. CLEAN INVENTORY MOVEMENT

In [35]:
inv_move.head()

  product_id warehouse_id  change_qty   reason        date
0  PROD00578        WH005          44  Restock  2024-04-30
1  PROD00704        WH006          82  Restock  2023-01-16
2  PROD00453        WH005           0  Restock  2023-07-20
3  PROD00702        WH007         -52     Sale  2023-10-17
4  PROD00119        WH009         -47     Sale  2024-10-22

In [36]:
print(inv_move.dtypes)

product_id      object
warehouse_id    object
change_qty       int64
reason          object
date            object
dtype: object

In [37]:
inv_move_max_lengths = inv_move.astype(str).apply(lambda x: x.str.len()).max()
print(inv_move_max_lengths)

product_id       9
warehouse_id     5
change_qty       4
reason           7
date            10
dtype: int64

In [38]:
inv_move['date'] = pd.to_datetime(inv_move['date'], errors= 'coerce')
inv_move.dtypes

product_id              object
warehouse_id            object
change_qty               int64
reason                  object
date            datetime64[ns]
dtype: object

7. CLEAN STORES

In [39]:
store.head()

   store_id       city       store_type
0  STORE000      Delhi  Warehouse Store
1  STORE001  Ahmedabad             Mall
2  STORE002     Jaipur  Warehouse Store
3  STORE003  Hyderabad      High Street
4  STORE004       Pune      High Street

In [40]:
print(store.dtypes)

store_id      object
city          object
store_type    object
dtype: object

In [41]:
store_max_lengths = store.astype(str).apply(lambda x: x.str.len()).max()
print(store_max_lengths)

store_id       8
city           9
store_type    15
dtype: int64

8. CLEAN WAREHOUSES

In [42]:
ware.head()

  warehouse_id       city  capacity
0        WH000    Chennai     41284
1        WH001      Delhi     30352
2        WH002  Bangalore     11943
3        WH003       Pune     31562
4        WH004       Pune     48079

In [43]:
print(ware.dtypes)

warehouse_id    object
city            object
capacity         int64
dtype: object

In [44]:
ware_max_lengths = ware.astype(str).apply(lambda x: x.str.len()).max()
print(ware_max_lengths)

warehouse_id    5
city            9
capacity        5
dtype: int64

In [45]:
pip install pandas sqlalchemy psycopg2

Requirement already satisfied: pandas in c:\users\zakym_xg1tqji\anaconda3\lib\site-packages (2.2.3)Note: you may need to restart the kernel to use updated packages.

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000019882D3BA10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/psycopg2/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000019882F91A90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/psycopg2/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000019882F91D10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/psycopg2/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000019882F91F90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/psycopg2/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000019882F92210>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/psycopg2/
ERROR: Could not find a version that satisfies the requirement psycopg2 (from versions: none)
ERROR: No matching distribution found for psycopg2

Requirement already satisfied: sqlalchemy in c:\users\zakym_xg1tqji\anaconda3\lib\site-packages (2.0.39)

In [46]:
from sqlalchemy import create_engine

In [47]:
engine = create_engine('postgresql+psycopg2://postgres:datadriven@localhost:5432/omni_sql')
engine.connect()

In [48]:
pd.read_sql("SELECT 100;", engine)

   ?column?
0       100

In [53]:
#prod.to_sql('cl_products', con = engine, index = False, if_exists = 'append')
#ord.to_sql('cl_orders', con = engine, index = False, if_exists = 'append')
#cust.to_sql('cl_customers', con = engine, index = False, if_exists = 'append')
#ord_it.to_sql('cl_orditem', con = engine, index = False, if_exists = 'append')
#inv.to_sql('cl_inventory', con = engine, index = False, if_exists = 'append')
#inv_move.to_sql('cl_invmove', con = engine, index = False, if_exists = 'append')
#store.to_sql('cl_stores', con = engine, index = False, if_exists = 'append')
#ware.to_sql('cl_warehouses', con = engine, index = False, if_exists = 'append')